##
## Test Suites
##

    modified.files.includes[relevant][portal-mobile-device-recognition-rule]=**

    relevant.rule.names=\
        portal-mobile-device-recognition-rule

    test.batch.names[relevant][portal-mobile-device-recognition-rule]

##
## Testray
##

    testray.main.component.name=Mobile Device Rules