##
## Test Suites
##

    modified.files.includes[relevant][portal-upgrade-impl-rule]=*

    relevant.rule.names=\
        portal-upgrade-impl-rule

    test.batch.names[relevent][portal-upgrade-impl-rule]

##
## Testray
##

    testray.main.component.name=Database Upgrade Framework