##
## Test Suites
##

	test.batch.names[relevent][image-rule]

	relevant.rule.names=\
		image-rule

	modified.files.includes[relevant][image-rule]=*
##
## Testray
##

    testray.main.component.name=Document Management