##
## Test Suites
##

    modified.files.includes[relevant][image-rule]=**

    relevant.rule.names=\
        image-rule

    test.batch.names[relevant][image-rule]

##
## Testray
##

    testray.main.component.name=Document Management