##
## Test Suites
##


	modified.files.includes[relevant][image-rule]=*

	relevant.rule.names=\
		image-rule

	test.batch.names[relevent][image-rule]
##
## Testray
##

    testray.main.component.name=Document Management