##
## Test Suites
##

    modified.files.includes[relevant][ant-bnd-rule]=**

    relevant.rule.names=\
        ant-bnd-rule

    test.batch.names[relevant][ant-bnd-rule]

##
## Testray
##

    testray.main.component.name=Dev Tools