##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	ant-bnd-rule

modified.files.includes[relevant][ant-bnd-rule]=*
##
## Testray
##

    testray.main.component.name=Dev Tools