##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]=\
	functional-bundle-tomcat-mysql57-jdk8,\
	functional-tomcat*-mysql*-jdk8,\
	functional-tomcat*-mysql*-jdk8

relevant.rule.names=\
	frontend-editor-rule

modified.files.includes[relevant][frontend-editor-rule]=*

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][frontend-editor-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][frontend-editor-rule]=\
        (portal.acceptance == true) AND \
        (testray.component.names ~ "WYSIWYG")

##
## Testray
##

    testray.main.component.name=WYSIWYG