##
## Test Suites
##


	modified.files.includes[relevant][analytics-rule]=**

	relevant.rule.names=\
		analytics-rule

	test.batch.names[relevant][analytics-rule]=\
		functional-tomcat90-mysql157-jdk8

    modules.includes.required.functional[relevant][analytics-rule]=\
        apps/content-dashboard,\
        apps/segments

    modules.includes.required.test.batch.class.names.includes[relevant][analytics-rule]=\
        apps/content-dashboard/**/*Test.java,\
        apps/segments/**/*Test.java


    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][analytics-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][analytics-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "A/B Test") OR \
            (testray.main.component.name ~ "A/B Test")\
        )

##
## Testray
##

    testray.main.component.name=Analytics Cloud