##
## Test Suites
##

    test.batch.names[relevent][site-initializer-rule]

    relevant.rule.names=\
        site-initializer-rule

    modified.files.includes[relevant][site-initializer-rule]=*

##
## Testray
##

    testray.main.component.name=Site Initializer Extender