##
## Test Suites
##

	test.batch.names[relevant][site-initializer-rule]

	relevant.rule.names=\
		site-initializer-rule

	modified.files.includes[relevant][site-initializer-rule]=*
##
## Testray
##

    testray.main.component.name=Site Initializer Extender