##
## Test Suites
##


	modified.files.includes[relevant][site-initializer-rule]=*

	relevant.rule.names=\
		site-initializer-rule

	test.batch.names[relevent][site-initializer-rule]
##
## Testray
##

    testray.main.component.name=Site Initializer Extender