##
## Test Suites
##

    modified.files.includes[relevant][portal-relationship-rule]=**

    relevant.rule.names=\
        portal-relationship-rule

    test.batch.names[relevant][portal-relationship-rule]

##
## Testray
##

    testray.main.component.name=Portal Services