##
## Test Suites
##

    modified.files.includes[relevant][asset-publisher-layout-prototype-rule]=**

    relevant.rule.names=\
        asset-publisher-layout-prototype-rule

    test.batch.names[relevant][asset-publisher-layout-prototype-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-publisher-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Asset Publisher Widget