##
## Test Suites
##

    modified.files.includes[relevant][asset-web-rule]=**

    relevant.rule.names=\
        asset-web-rule

    test.batch.names[relevant][asset-web-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-test/**/*Test.java