##
## Test Suites
##

	test.batch.names[relevent][changeset-rule]

	relevant.rule.names=\
		changeset-rule

	modified.files.includes[relevant][changeset-rule]=*

    modules.includes.required[relevant][changeset-rule]=\
        apps/staging

##
## Testray
##

    testray.main.component.name=Staging