##
## Test Suites
##


	modified.files.includes[relevant][changeset-rule]=**

	relevant.rule.names=\
		changeset-rule

	test.batch.names[relevant][changeset-rule]

    modules.includes.required[relevant][changeset-rule]=\
        apps/staging

##
## Testray
##

    testray.main.component.name=Staging