##
## Test Suites
##

    modified.files.includes[relevant][asset-categories-admin-web-api-rule]=**

    relevant.rule.names=\
        asset-categories-admin-web-api-rule

    test.batch.names[relevant][asset-categories-admin-web-api-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-categories-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Categories