##
## Test Suites
##


	modified.files.includes[relevant][redirect-service-rule]=*

	relevant.rule.names=\
		redirect-service-rule

	test.batch.names[relevent][redirect-service-rule]=\
		functional-upgrade*-tomcat*-mysql*-jdk8
##
## Relevant
##

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant][redirect-service-rule]=\
        (testray.component.names ~ "Upgrades WEM") AND \
        (testray.main.component.name == "URL Redirections")

##
## Testray
##

    testray.main.component.name=URL Redirections