##
## Test Suites
##

    modified.files.includes[relevant][archived-rule]=*

    relevant.rule.names=\
        archived-rule

    test.batch.names[relevent][archived-rule]

##
## Testray
##

    testray.main.component.name=Archived Apps