##
## Test Suites
##

	test.batch.names[relevent][archived-rule]

	relevant.rule.names=\
		archived-rule

	modified.files.includes[relevant][archived-rule]=*
##
## Testray
##

    testray.main.component.name=Archived Apps