##
## Test Suites
##

    modified.files.includes[relevant][osgi-service-tracker-collections-test-rule]=*

    relevant.rule.names=\
        osgi-service-tracker-collections-test-rule

    test.batch.names[relevent][osgi-service-tracker-collections-test-rule]

##
## Testray
##

    testray.main.component.name=Portal Services