##
## Test Suites
##

    modified.files.includes[relevant][portal-osgi-debug-rule]=*

    relevant.rule.names=\
        portal-osgi-debug-rule

    test.batch.names[relevent][portal-osgi-debug-rule]

##
## Testray
##

    testray.main.component.name=Portal Services