##
## Test Suites
##

    modified.files.includes[relevant][repository-rule]=**

    relevant.rule.names=\
        repository-rule

    test.batch.names[relevant][repository-rule]

##
## Testray
##

    testray.main.component.name=Document Management