##
## Test Suites
##

	test.batch.names[relevent][repository-rule]

	relevant.rule.names=\
		repository-rule

	modified.files.includes[relevant][repository-rule]=*
##
## Testray
##

    testray.main.component.name=Document Management