##
## Test Suites
##

    test.batch.names[relevent][website-rule]

    relevant.rule.names=\
        website-rule

    modified.files.includes[relevant][website-rule]=*

##
## Testray
##

    testray.main.component.name=Personal Data