##
## Test Suites
##


	modified.files.includes[relevant][website-rule]=*

	relevant.rule.names=\
		website-rule

	test.batch.names[relevent][website-rule]
##
## Testray
##

    testray.main.component.name=Personal Data