##
## Test Suites
##


	modified.files.includes[relevant][portal-transaction-rule]=**

	relevant.rule.names=\
		portal-transaction-rule

	test.batch.names[relevant][portal-transaction-rule]
##
## Testray
##

    testray.main.component.name=Portal Services