##
## Test Suites
##

	test.batch.names[relevent][portal-transaction-rule]

	relevant.rule.names=\
		portal-transaction-rule

	modified.files.includes[relevant][portal-transaction-rule]=*
##
## Testray
##

    testray.main.component.name=Portal Services