##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]=\
	functional-bundle-tomcat-mysql57-jdk8,\
	functional-tomcat*-mysql*-jdk8,\
	functional-tomcat*-mysql*-jdk8

relevant.rule.names=\
	bulk-rule

modified.files.includes[relevant][bulk-rule]=*

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][bulk-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][bulk-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Bulk Editing") OR \
            (testray.main.component.name ~ "Bulk Editing")\
        )

##
## Testray
##

    testray.main.component.name=Bulk Editing