##
## Test Suites
##

    test.batch.names[relevent][bean-portlet-rule]

    relevant.rule.names=\
        bean-portlet-rule

    modified.files.includes[relevant][bean-portlet-rule]=*

##
## Testray
##

    testray.main.component.name=Bean Portlet