##
## Test Suites
##


	modified.files.includes[relevant][bean-portlet-rule]=**

	relevant.rule.names=\
		bean-portlet-rule

	test.batch.names[relevant][bean-portlet-rule]
##
## Testray
##

    testray.main.component.name=Bean Portlet