##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	data-cleanup-rule

modified.files.includes[relevant][data-cleanup-rule]=*
##
## Testray
##

    testray.main.component.name=Data Cleanup