##
## Test Suites
##

    test.batch.names[relevent][antivirus-rule]

    relevant.rule.names=\
        antivirus-rule

    modified.files.includes[relevant][antivirus-rule]=*

##
## Testray
##

    testray.main.component.name=Antivirus