##
## Test Suites
##

    modified.files.includes[relevant][salesforce-connector-rule]=**

    relevant.rule.names=\
        salesforce-connector-rule

    test.batch.names[relevant][salesforce-connector-rule]

##
## Testray
##

    testray.main.component.name=Commerce