##
## Test Suites
##

    test.batch.names[relevent][salesforce-connector-rule]

    relevant.rule.names=\
        salesforce-connector-rule

    modified.files.includes[relevant][salesforce-connector-rule]=*

##
## Testray
##

    testray.main.component.name=Commerce