##
## Test Suites
##

    modified.files.includes[relevant][websocket-rule]=**

    relevant.rule.names=\
        websocket-rule

    test.batch.names[relevant][websocket-rule]

##
## Testray
##

    testray.main.component.name=Portal Services