##
## Test Suites
##


	modified.files.includes[relevant][external-reference-rule]=*

	relevant.rule.names=\
		external-reference-rule

	test.batch.names[relevent][external-reference-rule]
##
## Testray
##

    testray.main.component.name=Portal Services