##
## Test Suites
##

    test.batch.names[relevent][commerce-punchout-rule]

    relevant.rule.names=\
        commerce-punchout-rule

    modified.files.includes[relevant][commerce-punchout-rule]=*

##
## Testray
##

    testray.main.component.name=Commerce