##
## Test Suites
##

    modified.files.includes[relevant][commerce-punchout-rule]=**

    relevant.rule.names=\
        commerce-punchout-rule

    test.batch.names[relevant][commerce-punchout-rule]

##
## Testray
##

    testray.main.component.name=Commerce