##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	asset-browser-web-rule

modified.files.includes[relevant][asset-browser-web-rule]=*

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-test/**/*Test.java