##
## Test Suites
##

    modified.files.includes[relevant][asset-browser-web-rule]=*

    relevant.rule.names=\
        asset-browser-web-rule

    test.batch.names[relevent][asset-browser-web-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-test/**/*Test.java