##
## Test Suites
##

    modified.files.includes[relevant][social-rule]=*

    relevant.rule.names=\
        social-rule

    test.batch.names[relevent][social-rule]

##
## Testray
##

    testray.main.component.name=Social Bookmarks