##
## Test Suites
##

    modified.files.includes[relevant][portal-rule]=**

    relevant.rule.names=\
        portal-rule

    test.batch.names[relevant][portal-rule]

##
## Testray
##

    testray.main.component.name=Portal Services