##
## Test Suites
##

    modified.files.includes[relevant][asset-publisher-test-rule]=*

    relevant.rule.names=\
        asset-publisher-test-rule

    test.batch.names[relevent][asset-publisher-test-rule]

##
## Testray
##

    testray.main.component.name=Asset Publisher Widget