##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	frontend-icons-rule

modified.files.includes[relevant][frontend-icons-rule]=*
##
## Testray
##

    testray.main.component.name=User Interface