##
## Test Suites
##

    modified.files.includes[relevant][frontend-icons-rule]=*

    relevant.rule.names=\
        frontend-icons-rule

    test.batch.names[relevent][frontend-icons-rule]

##
## Testray
##

    testray.main.component.name=User Interface