##
## Test Suites
##


	modified.files.includes[relevant][portal-portlet-bridge-rule]=*

	relevant.rule.names=\
		portal-portlet-bridge-rule

	test.batch.names[relevent][portal-portlet-bridge-rule]
##
## Testray
##

    testray.main.component.name=Portal Services