##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	portal-portlet-bridge-rule

modified.files.includes[relevant][portal-portlet-bridge-rule]=*
##
## Testray
##

    testray.main.component.name=Portal Services