##
## Test Suites
##

    modified.files.includes[relevant][flags-rule]=*

    relevant.rule.names=\
        flags-rule

    test.batch.names[relevent][flags-rule]

##
## Testray
##

    testray.main.component.name=Flags