##
## Test Suites
##

    test.batch.names[relevent][flags-rule]

    relevant.rule.names=\
        flags-rule

    modified.files.includes[relevant][flags-rule]=*

##
## Testray
##

    testray.main.component.name=Flags