##
## Test Suites
##

    test.batch.names[relevant][diff-rule]

    relevant.rule.names=\
        diff-rule

    modified.files.includes[relevant][diff-rule]=*

##
## Testray
##

    testray.main.component.name=Portal Services