##
## Test Suites
##

    modified.files.includes[relevant][diff-rule]=**

    relevant.rule.names=\
        diff-rule

    test.batch.names[relevant][diff-rule]

##
## Testray
##

    testray.main.component.name=Portal Services