##
## Modules
##

    modules.includes.required[relevant][portal-odata-rule]=\
        apps/headless

##
## Test Suites
##

    test.batch.names[relevent][portal-odata-rule]

    relevant.rule.names=\
        portal-odata-rule

    modified.files.includes[relevant][portal-odata-rule]=*

##
## Testray
##

    testray.main.component.name=Headless