##
## Test Suites
##

    modified.files.includes[relevant][portal-odata-rule]=**

    relevant.rule.names=\
        portal-odata-rule

    test.batch.names[relevant][portal-odata-rule]

    modules.includes.required[relevant][portal-odata-rule]=\
        apps/headless

##
## Testray
##

    testray.main.component.name=Headless