##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	portal-odata-rule

modified.files.includes[relevant][portal-odata-rule]=*

    modules.includes.required[relevant][portal-odata-rule]=\
        apps/headless

##
## Testray
##

    testray.main.component.name=Headless