##
## Test Suites
##


	modified.files.includes[relevant][plugins-admin-rule]=*

	relevant.rule.names=\
		plugins-admin-rule

	test.batch.names[relevent][plugins-admin-rule]
##
## Testray
##

    testray.main.component.name=Components Admin