##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	plugins-admin-rule

modified.files.includes[relevant][plugins-admin-rule]=*
##
## Testray
##

    testray.main.component.name=Components Admin