##
## Test Suites
##

    test.batch.names[relevent][push-notifications-rule]

    relevant.rule.names=\
        push-notifications-rule

    modified.files.includes[relevant][push-notifications-rule]=*

##
## Testray
##

    testray.main.component.name=Notifications