##
## Test Suites
##


	modified.files.includes[relevant][push-notifications-rule]=*

	relevant.rule.names=\
		push-notifications-rule

	test.batch.names[relevent][push-notifications-rule]
##
## Testray
##

    testray.main.component.name=Notifications