##
## Test Suites
##


	modified.files.includes[relevant][push-notifications-rule]=**

	relevant.rule.names=\
		push-notifications-rule

	test.batch.names[relevant][push-notifications-rule]
##
## Testray
##

    testray.main.component.name=Notifications