##
## Test Suites
##


	modified.files.includes[relevant][release-feature-flag-rule]=**

	relevant.rule.names=\
		release-feature-flag-rule

	test.batch.names[relevant][release-feature-flag-rule]
##
## Testray
##

    testray.main.component.name=Feature Flags