##
## Test Suites
##

    modified.files.includes[relevant][asset-tags-validator-rule]=*

    relevant.rule.names=\
        asset-tags-validator-rule

    test.batch.names[relevent][asset-tags-validator-rule]

##
## Testray
##

    testray.main.component.name=Asset Publisher Widget