##
## Test Suites
##


	modified.files.includes[relevant][marketplace-rule]=*

	relevant.rule.names=\
		marketplace-rule

	test.batch.names[relevent][marketplace-rule]
##
## Testray
##

    testray.main.component.name=Marketplace