##
## Test Suites
##

    test.batch.names[relevent][marketplace-rule]

    relevant.rule.names=\
        marketplace-rule

    modified.files.includes[relevant][marketplace-rule]=*

##
## Testray
##

    testray.main.component.name=Marketplace