##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
    css-builder-rule

modified.files.includes[relevant][css-builder-rule]=*

##
## Testray
##

    testray.main.component.name=Dev Tools