##
## Test Suites
##


	modified.files.includes[relevant][css-builder-rule]=**

	relevant.rule.names=\
		css-builder-rule

	test.batch.names[relevant][css-builder-rule]
##
## Testray
##

    testray.main.component.name=Dev Tools