##
## Test Suites
##

    modified.files.includes[relevant][asset-list-web-rule]=**

    relevant.rule.names=\
        asset-list-web-rule

    test.batch.names[relevant][asset-list-web-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-list-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Collections