##
## Test Suites
##


	modified.files.includes[relevant][asset-categories-admin-web-rule]=*

	relevant.rule.names=\
		asset-categories-admin-web-rule

	test.batch.names[relevent][asset-categories-admin-web-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-categories-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Categories