##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	image-uploader-rule

modified.files.includes[relevant][image-uploader-rule]=*
##
## Testray
##

    testray.main.component.name=Image Uploader