##
## Test Suites
##

    modified.files.includes[relevant][image-uploader-rule]=*

    relevant.rule.names=\
        image-uploader-rule

    test.batch.names[relevent][image-uploader-rule]

##
## Testray
##

    testray.main.component.name=Image Uploader