##
## Test Suites
##


	modified.files.includes[relevant][portal-tools-theme-builder-rule]=*

	relevant.rule.names=\
		portal-tools-theme-builder-rule

	test.batch.names[relevent][portal-tools-theme-builder-rule]
##
## Testray
##

    testray.main.component.name=Dev Tools