##
## Test Suites
##

    test.batch.names[relevent][map-rule]

    relevant.rule.names=\
        map-rule

    modified.files.includes[relevant][map-rule]=*

##
## Testray
##

    testray.main.component.name=Maps