##
## Test Suites
##

    modified.files.includes[relevant][map-rule]=**

    relevant.rule.names=\
        map-rule

    test.batch.names[relevant][map-rule]

##
## Testray
##

    testray.main.component.name=Maps