##
## Test Suites
##


	modified.files.includes[relevant][mobile-device-rules-rule]=**

	relevant.rule.names=\
		mobile-device-rules-rule

	test.batch.names[relevant][mobile-device-rules-rule]
##
## Testray
##

    testray.main.component.name=Mobile Device Rules