##
## Test Suites
##

    test.batch.names[relevent][headless-form-rule]=\
        functional-bundle-tomcat-mysql57-jdk8,\
        functional-tomcat*-mysql*-jdk8,\
        functional-tomcat*-mysql*-jdk8

    relevant.rule.names=\
        headless-form-rule

    modified.files.includes[relevant][headless-form-rule]=*

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][headless-form-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][hea