##
## Test Suites
##


	modified.files.includes[relevant][portal-validation-rule]=**

	relevant.rule.names=\
		portal-validation-rule

	test.batch.names[relevant][portal-validation-rule]
##
## Testray
##

    testray.main.component.name=Staging