##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	portal-validation-rule

modified.files.includes[relevant][portal-validation-rule]=*
##
## Testray
##

    testray.main.component.name=Staging