##
## Test Suites
##


	modified.files.includes[relevant][asset-vocabulary-item-selector-api-rule]=**

	relevant.rule.names=\
		asset-vocabulary-item-selector-api-rule

	test.batch.names[relevant][asset-vocabulary-item-selector-api-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Tags