##
## Test Suites
##


	modified.files.includes[relevant][enterprise-product-notification-rule]=**

	relevant.rule.names=\
		enterprise-product-notification-rule

	test.batch.names[relevant][enterprise-product-notification-rule]
##
## Testray
##

    testray.main.component.name=Notification