##
## Relevant
##

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant][document-library-sync-service-rule]=\
        (testray.component.names == "Document Management") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Test Suites
##

    test.batch.names[relevent][document-library-sync-service-rule]=\
        functional-upgrade*-tomcat*-mysql*-jdk8

    relevant.rule.names=\
        document-library-sync-service-rule

    modified.files.includes[relevant][document-library-sync-service-rule]=*

##
## Testray
##

    testray.main.component.name=Document Management