##
## Test Suites
##


	modified.files.includes[relevant][user-rule]=*

	relevant.rule.names=\
		user-rule

	test.batch.names[relevent][user-rule]
##
## Testray
##

    testray.main.component.name=Users and Organizations