##
## Test Suites
##

    test.batch.names[relevent][user-rule]

    relevant.rule.names=\
        user-rule

    modified.files.includes[relevant][user-rule]=*

##
## Testray
##

    testray.main.component.name=Us