##
## Test Suites
##

    modified.files.includes[relevant][commerce-demo-pack-rule]=*

    relevant.rule.names=\
        commerce-demo-pack-rule

    test.batch.names[relevent][commerce-demo-pack-rule]

##
## Testray
##

    testray.main.component.name=Commerce