##
## Test Suites
##


	modified.files.includes[relevant][microsoft-translator-rule]=**

	relevant.rule.names=\
		microsoft-translator-rule

	test.batch.names[relevant][microsoft-translator-rule]
##
## Testray
##

    testray.main.component.name=Translations Management