##
## Test Suites
##

	test.batch.names[relevent][monitoring-rule]

	relevant.rule.names=\
		monitoring-rule

	modified.files.includes[relevant][monitoring-rule]=*
##
## Testray
##

    testray.main.component.name=Monitoring