##
## Test Suites
##

    modified.files.includes[relevant][monitoring-rule]=**

    relevant.rule.names=\
        monitoring-rule

    test.batch.names[relevant][monitoring-rule]

##
## Testray
##

    testray.main.component.name=Monitoring