##
## Test Suites
##

    test.batch.names[relevent][portal-template-rule]

    relevant.rule.names=\
        portal-template-rule

    modified.files.includes[relevant][portal-template-rule]=*

##
## Testray
##

    testray.main.component.name=Templates Engine