##
## Test Suites
##

    modified.files.includes[relevant][portal-template-rule]=*

    relevant.rule.names=\
        portal-template-rule

    test.batch.names[relevent][portal-template-rule]

##
## Testray
##

    testray.main.component.name=Templates Engine