##
## Test Suites
##

	test.batch.names[relevent][osb-rule]

	relevant.rule.names=\
		osb-rule

	modified.files.includes[relevant][osb-rule]=*
##
## Testray
##

    testray.main.component.name=Customer Portal