##
## Test Suites
##

    test.batch.names[relevant][osb-rule]

    relevant.rule.names=\
        osb-rule

    modified.files.includes[relevant][osb-rule]=*

##
## Testray
##

    testray.main.component.name=Customer Portal