##
## Test Suites
##

    modified.files.includes[relevant][locked-items-rule]=*

    relevant.rule.names=\
        locked-items-rule

    test.batch.names[relevent][locked-items-rule]

##
## Testray
##

    testray.main.component.name=Locked Items