##
## Test Suites
##

    modified.files.includes[relevant][expando-rule]=**

    relevant.rule.names=\
        expando-rule

    test.batch.names[relevant][expando-rule]

##
## Testray
##

    testray.main.component.name=Custom Fields