##
## Test Suites
##

	test.batch.names[relevent][expando-rule]

	relevant.rule.names=\
		expando-rule

	modified.files.includes[relevant][expando-rule]=*
##
## Testray
##

    testray.main.component.name=Custom Fields