##
## Test Suites
##


	modified.files.includes[relevant][portlet-rule]=**

	relevant.rule.names=\
		portlet-rule

	test.batch.names[relevant][portlet-rule]
##
## Testray
##

    testray.main.component.name=Portal Services