##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	portlet-rule

modified.files.includes[relevant][portlet-rule]=*
##
## Testray
##

    testray.main.component.name=Portal Services