##
## Test Suites
##

	test.batch.names[relevant][microblogs-rule]

	relevant.rule.names=\
		microblogs-rule

	modified.files.includes[relevant][microblogs-rule]=*
##
## Testray
##

    testray.main.component.name=Microblogs