##
## Test Suites
##

    modified.files.includes[relevant][microblogs-rule]=*

    relevant.rule.names=\
        microblogs-rule

    test.batch.names[relevent][microblogs-rule]

##
## Testray
##

    testray.main.component.name=Microblogs