##
## Test Suites
##

    modified.files.includes[relevant][portlet-dependency-factory-rule]=*

    relevant.rule.names=\
        portlet-dependency-factory-rule

    test.batch.names[relevent][portlet-dependency-factory-rule]

##
## Testray
##

    testray.main.component.name=Portal Services