##
## Relevant
##

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant][sharing-web-rule][sharing-web-rule]=\
        (testray.component.names == "Asset Sharing") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Test Suites
##

    test.batch.names[relevent][sharing-web-rule]=\
        functional-upgrade*-tomcat*-mysql*-jdk8

    relevant.rule.names=\
        sharing-web-rule

    modified.files.includes[relevant][sharing-web-rule]=*

##
## Test Suites
##

    test.batch.names[relevent][sharing-web-rule]=\
        functional-upgrade*-tomcat*-mysql*-jdk8

    relevant.rule.names=\
        sharing-web-rule

    modified.files.includes[relevant][sharing-web-rule][sharing-web-rule]=*

##
## Testray
##

    testray.main.component.name=Asset Sharing