##
## Test Suites
##

    modified.files.includes[relevant][invitation-rule]=**

    relevant.rule.names=\
        invitation-rule

    test.batch.names[relevant][invitation-rule]

##
## Testray
##

    testray.main.component.name=Invite Members