##
## Test Suites
##

	test.batch.names[relevent][invitation-rule]

	relevant.rule.names=\
		invitation-rule

	modified.files.includes[relevant][invitation-rule]=*
##
## Testray
##

    testray.main.component.name=Invite Members