##
## Test Suites
##


	modified.files.includes[relevant][portal-list-type-test-rule]=**

	relevant.rule.names=\
		portal-list-type-test-rule

	test.batch.names[relevant][portal-list-type-test-rule]
##
## Testray
##

    testray.main.component.name=Portal List Type