##
## Test Suites
##

    modified.files.includes[relevant][asset-tags-service-rule]=**

    relevant.rule.names=\
        asset-tags-service-rule

    test.batch.names[relevant][asset-tags-service-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Tags