##
## Test Suites
##

    modified.files.includes[relevant][text-localizer-rule]=*

    relevant.rule.names=\
        text-localizer-rule

    test.batch.names[relevent][text-localizer-rule]

##
## Testray
##

    testray.main.component.name=Users and Organizations