##
## Test Suites
##

    modified.files.includes[relevant][xstream-rule]=*

    relevant.rule.names=\
        xstream-rule

    test.batch.names[relevent][xstream-rule]

##
## Testray
##

    testray.main.component.name=Portal Services