##
## Test Suites
##

	test.batch.names[relevent][xstream-rule]

	relevant.rule.names=\
		xstream-rule

	modified.files.includes[relevant][xstream-rule]=*
##
## Testray
##

    testray.main.component.name=Portal Services