##
## Test Suites
##


	modified.files.includes[relevant][portal-security-audit-rule]=*

	relevant.rule.names=\
		portal-security-audit-rule

	test.batch.names[relevent][portal-security-audit-rule]
##
## Testray
##

    testray.main.component.name=Audit