##
## Test Suites
##
##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	asset-publisher-web-rule

modified.files.includes[relevant][asset-publisher-web-rule]=*

relevant.rule.names=\
	asset-publisher-web-rule

modified.files.includes[relevant][asset-publisher-web-rule]=*

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-publisher-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Asset Publisher Widget