    test.batch.names[relevent][my-subscriptions-rule]

    relevant.rule.names=\
        my-subscriptions-rule

    modified.files.includes[relevant][my-subscriptions-rule]=*

##
## Testray
##

    testray.main.component.name=My Subscriptions