##
## Test Suites
##

    modified.files.includes[relevant][rss-rule]=*

    relevant.rule.names=\
        rss-rule

    test.batch.names[relevent][rss-rule]=\
        functional-bundle-tomcat-mysql57-jdk8,\
        functional-tomcat*-mysql*-jdk8,\
        functional-tomcat*-mysql*-jdk8

    modules.includes.required.functional[relevant][rss-rule]=\
        apps/asset

    modules.includes.required.test.batch.class.names.includes[modules-unit-jdk8][relevant][rss-rule]=\
        apps/asset/**/src/test/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-integration-*-jdk8][relevant][rss-rule]=\
        apps/asset/**/src/testIntegration/**/*Test.java

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][rss-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][rss-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.main.component.name ~ "Asset Publisher Widget") OR \
            (testray.main.component.name ~ "RSS Publisher Widget")\
        )

##
## Testray
##

    testray.main.component.name=RSS