##
## Test Suites
##


	modified.files.includes[relevant][portal-configuration-rule]=*

	relevant.rule.names=\
		portal-configuration-rule

	test.batch.names[relevent][portal-configuration-rule]
##
## Testray
##

    testray.main.component.name=Portal Configuration