##
## Test Suites
##

	test.batch.names[relevant][analytics-rule]

	relevant.rule.names=\
		analytics-rule

	modified.files.includes[relevant][analytics-rule]=*
##
## Testray
##

    testray.main.component.name=Analytics Cloud