##
## Test Suites
##

    test.batch.names[relevent][analytics-rule]

    relevant.rule.names=\
        analytics-rule

    modified.files.includes[relevant][analytics-rule]=*

##
## Testray
##

    testray.main.component.name=Analytics Cloud