##
## Test Suites
##

    modified.files.includes[relevant][analytics-rule]=*

    relevant.rule.names=\
        analytics-rule

    test.batch.names[relevent][analytics-rule]

##
## Testray
##

    testray.main.component.name=Analytics Cloud