##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]=\
	functional-tomcat*-mysql*-jdk8

relevant.rule.names=\
	portal-properties-swapper-rule

modified.files.includes[relevant][portal-properties-swapper-rule]=*

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][portal-properties-swapper-rule]=\
        (testray.main.component.name == "Setup Wizard")