##
## Modules
##

    modules.includes.required[relevant][accessibility-rule]=\
        apps/accessibility

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][accessibility-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Accessibility Menu") OR \
            (testray.main.component.name ~ "Accessibility Menu")\
        )

##
## Test Suites
##

    test.batch.names[relevent][accessibility-rule]=\
        functional-tomcat*-mysql*-jdk8

    relevant.rule.names=\
        accessibility-rule

    modified.files.includes[relevant][accessibility-rule]=*

##
## Testray
##

    testray.main.component.name=Accessibility Menu