##
## Test Suites
##

	test.batch.names[relevent][asset-taglib-rule]

	relevant.rule.names=\
		asset-taglib-rule

	modified.files.includes[relevant][asset-taglib-rule]=*
##
## Test Suites
##

	test.batch.names[relevent][asset-taglib-rule]

	relevant.rule.names=\
		asset-taglib-rule

	modified.files.includes[relevant][asset-taglib-rule][asset-taglib-rule]=*
##
## Modules
##

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Tags