##
## Test Suites
##

    modified.files.includes[relevant][password-policies-admin-rule]=*

    relevant.rule.names=\
        password-policies-admin-rule

    test.batch.names[relevent][password-policies-admin-rule]

##
## Testray
##

    testray.main.component.name=Password Policies