##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]=\
	functional-bundle-tomcat-mysql57-jdk8,\
	functional-tomcat*-mysql*-jdk8,\
	functional-tomcat*-mysql*-jdk8,\
	functional-upgrade-tomcat*-mysql*-jdk8

relevant.rule.names=\
	search-experiences-rule

modified.files.includes[relevant][search-experiences-rule]=*
##
## Backend Tests
##

    modules.includes.required[relevant][search-experiences-rule]=\
        apps/portal-search,\
        apps/portal-search-elasticsearch7

##
## Functional Tests
##

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][search-experiences-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][search-experiences-rule]=\
        (test.class.name == Blueprints) OR \
        (test.class.name == SemanticSearch)

    test.batch.run.property.query[functional-upgrade-tomcat*-mysql*-jdk8][relevant][search-experiences-rule]=\
        (portal.suite.search.engine ~ "elasticsearch7") AND \
        (testray.main.component.name ~ "Upgrades Search")

##
## Testray
##

    testray.main.component.name=Search Experiences