##
## Test Suites
##

    modified.files.includes[relevant][portal-background-task-rule]=*

    relevant.rule.names=\
        portal-background-task-rule

    test.batch.names[relevent][portal-background-task-rule]

##
## Testray
##

    testray.main.component.name=Portal Services