    test.batch.names[relevent][configuration-admin-rule]

    relevant.rule.names=\
        configuration-admin-rule

    modified.files.includes[relevant][configuration-admin-rule]=*

##
## Testray
##

    testray.main.component.name=System Settings