##
## Test Suites
##


	modified.files.includes[relevant][configuration-admin-rule]=**

	relevant.rule.names=\
		configuration-admin-rule

	test.batch.names[relevant][configuration-admin-rule]
##
## Testray
##

    testray.main.component.name=System Settings