##
## Test Suites
##


	modified.files.includes[relevant][contacts-rule]=**

	relevant.rule.names=\
		contacts-rule

	test.batch.names[relevant][contacts-rule]
##
## Testray
##

    testray.main.component.name=Contacts Center