##
## Test Suites
##

    modified.files.includes[relevant][subscription-rule]=*

    relevant.rule.names=\
        subscription-rule

    test.batch.names[relevent][subscription-rule]

##
## Testray
##

    testray.main.component.name=My Subscriptions