##
## Test Suites
##

	test.batch.names[relevent][subscription-rule]

	relevant.rule.names=\
		subscription-rule

	modified.files.includes[relevant][subscription-rule]=*
##
## Testray
##

    testray.main.component.name=My Subscriptions