##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	asset-entry-rel-api-rule

modified.files.includes[relevant][asset-entry-rel-api-rule]=*

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-entry-rel-test/**/*Test.java