##
## Test Suites
##

    test.batch.names[relevent][portal-crypto-hash-rule]

    relevant.rule.names=\
        portal-crypto-hash-rule

    modified.files.includes[relevant][portal-crypto-hash-rule]=*

##
## Testray
##

    testray.main.component.name=Crypto