##
## Test Suites
##

    modified.files.includes[relevant][portal-crypto-hash-rule]=**

    relevant.rule.names=\
        portal-crypto-hash-rule

    test.batch.names[relevant][portal-crypto-hash-rule]

##
## Testray
##

    testray.main.component.name=Crypto