##
## Test Suites
##

    modified.files.includes[relevant][sdk-rule]=**

    relevant.rule.names=\
        sdk-rule

    test.batch.names[relevant][sdk-rule]

##
## Testray
##

    testray.main.component.name=Dev Tools