##
## Test Suites
##

	test.batch.names[relevant][sdk-rule]

	relevant.rule.names=\
		sdk-rule

	modified.files.includes[relevant][sdk-rule]=*
##
## Testray
##

    testray.main.component.name=Dev Tools