##
## Test Suites
##


	modified.files.includes[relevant][portal-upload-servlet-request-filter-rule]=**

	relevant.rule.names=\
		portal-upload-servlet-request-filter-rule

	test.batch.names[relevant][portal-upload-servlet-request-filter-rule]=\
		functional-tomcat90-mysql157-jdk8

    modules.includes.required[relevant][portal-upload-servlet-request-filter-rule]=\
        apps/document-library


    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][portal-upload-servlet-request-filter-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][portal-upload-servlet-request-filter-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Forms") OR \
            (testray.main.component.name ~ "Bundle Blacklist") OR \
            (testray.main.component.name ~ "Forms")\
        )