##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]=\
	functional-bundle-tomcat-mysql57-jdk8,\
	functional-tomcat*-mysql*-jdk8,\
	functional-tomcat*-mysql*-jdk8

relevant.rule.names=\
	headless-admin-taxonomy-rule

modified.files.includes[relevant][headless-admin-taxonomy-rule]=*

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][headless-admin-taxonomy-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][headless-admin-taxonomy-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Content Management Headless")

##
## Testray
##

testray.main.component.name=Content Management Headless