##
## Test Suites
##

	test.batch.names[relevent][server-rule]

	relevant.rule.names=\
		server-rule

	modified.files.includes[relevant][server-rule]=*
##
## Testray
##

    testray.main.component.name=Server Administration