##
## Test Suites
##


	modified.files.includes[relevant][server-rule]=*

	relevant.rule.names=\
		server-rule

	test.batch.names[relevent][server-rule]
##
## Testray
##

    testray.main.component.name=Server Administration