##
## Test Suites
##

	test.batch.names[relevent][journal-web-rule]

	relevant.rule.names=\
		journal-web-rule

	modified.files.includes[relevant][journal-web-rule]=*
##
## Test Suites
##

	test.batch.names[relevent][journal-web-rule]

	relevant.rule.names=\
		journal-web-rule

	modified.files.includes[relevant][journal-web-rule][journal-web-rule]=*
##
## Relevant
##

    playwright.test.project[playwright-js-tomcat90-mysql57-jdk8][relevant][journal-web-rule][journal-web-rule]=journal-web