##
## Test Suites
##


	modified.files.includes[relevant][on-demand-admin-rule]=**

	relevant.rule.names=\
		on-demand-admin-rule

	test.batch.names[relevant][on-demand-admin-rule]
##
## Testray
##

    testray.main.component.name=On Demand Admin