##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	on-demand-admin-rule

modified.files.includes[relevant][on-demand-admin-rule]=*
##
## Testray
##

    testray.main.component.name=On Demand Admin