##
## Test Suites
##

    modified.files.includes[relevant][view-count-rule]=*

    relevant.rule.names=\
        view-count-rule

    test.batch.names[relevent][view-count-rule]

##
## Testray
##

    testray.main.component.name=Util