##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	view-count-rule

modified.files.includes[relevant][view-count-rule]=*
##
## Testray
##

    testray.main.component.name=Util