##
## Test Suites
##

	test.batch.names[relevant][mail-rule]

	relevant.rule.names=\
		mail-rule

	modified.files.includes[relevant][mail-rule]=*
##
## Testray
##

    testray.main.component.name=Portal Services