##
## Test Suites
##

    modified.files.includes[relevant][mail-rule]=*

    relevant.rule.names=\
        mail-rule

    test.batch.names[relevent][mail-rule]

##
## Testray
##

    testray.main.component.name=Portal Services