##
## Test Suites
##

    modified.files.includes[relevant][portal-db-index-test-rule]=**

    relevant.rule.names=\
        portal-db-index-test-rule

    test.batch.names[relevant][portal-db-index-test-rule]

##
## Testray
##

    testray.main.component.name=Database Upgrade Framework