##
## Test Suites
##

    test.batch.names[relevent][cookie-rule]=\
        functional-bundle-tomcat-mysql57-jdk8,\
        functional-tomcat*-mysql*-jdk8,\
        functional-tomcat*-mysql*-jdk8

    relevant.rule.names=\
        cookie-rule

    modified.files.includes[relevant][cookie-rule]=*

##
## Test Suites
##

    test.batch.names[relevent][cookie-rule]=\
        functional-bundle-tomcat-mysql57-jdk8,\
        functional-tomcat*-mysql*-jdk8,\
        functional-tomcat*-mysql*-jdk8

    relevant.rule.names=\
        cookie-rule

    modified.files.includes[relevant][cookie-rule][cookie-rule]=*

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][cookie-rule][cookie-rule]}

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[relevant][cookie-rule][cookie-rule]=\
        **/cookies/**/src/test/**/*Test.java,\
        **/cookies/**/src/testIntegration/**/*Test.java

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][cookie-rule][cookie-rule]=\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Cookies") AND \
        (\
            (app.server.types == null) OR \
            (app.server.types ~ "tomcat")\
        ) AND \
        (\
            (database.types == null) OR \
            (database.types ~ "mysql")\
        )

##
## Testray
##

    testray.main.component.name=User Interface