##
## Test Suites
##


	modified.files.includes[relevant][imageio-plugins-rule]=**

	relevant.rule.names=\
		imageio-plugins-rule

	test.batch.names[relevant][imageio-plugins-rule]
##
## Testray
##

    testray.main.component.name=Portal Services