##
## Test Suites
##


	modified.files.includes[relevant][commerce-avalara-rule]=**

	relevant.rule.names=\
		commerce-avalara-rule

	test.batch.names[relevant][commerce-avalara-rule]
##
## Testray
##

    testray.main.component.name=Commerce