##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	notification-rule

modified.files.includes[relevant][notification-rule]=*
##
## Testray
##

    testray.main.component.name=Notifications