##
## Test Suites
##


	modified.files.includes[relevant][notification-rule]=**

	relevant.rule.names=\
		notification-rule

	test.batch.names[relevant][notification-rule]
##
## Testray
##

    testray.main.component.name=Notification