##
## Test Suites
##

	test.batch.names[relevant][notification-rule]

	relevant.rule.names=\
		notification-rule

	modified.files.includes[relevant][notification-rule]=*
##
## Testray
##

    testray.main.component.name=Notifications