##
## Test Suites
##

    modified.files.includes[relevant][reading-time-rule]=**

    relevant.rule.names=\
        reading-time-rule

    test.batch.names[relevant][reading-time-rule]

##
## Testray
##

    testray.main.component.name=Blogs