##
## Test Suites
##

    modified.files.includes[relevant][asset-info-api-rule]=*

    relevant.rule.names=\
        asset-info-api-rule

    test.batch.names[relevent][asset-info-api-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-test/**/*Test.java