##
## Test Suites
##

    modified.files.includes[relevant][portal-remote-rule]=*

    relevant.rule.names=\
        portal-remote-rule

    test.batch.names[relevent][portal-remote-rule]

##
## Testray
##

    testray.main.component.name=Portal Services