##
## Test Suites
##

    test.batch.names[relevent][portal-remote-rule]

    relevant.rule.names=\
        portal-remote-rule

    modified.files.includes[relevant][portal-remote-rule]=*

##
## Testray
##