##
## Test Suites
##

    test.batch.names[relevent][company-rule]

    relevant.rule.names=\
        company-rule

    modified.files.includes[relevant][company-rule]=*

##
## Testray
##

    testray.main.component.name=Virtual Instances