##
## Test Suites
##


	modified.files.includes[relevant][company-rule]=*

	relevant.rule.names=\
		company-rule

	test.batch.names[relevent][company-rule]
##
## Testray
##

    testray.main.component.name=Virtual Instances