##
## Test Suites
##

    modified.files.includes[relevant][portal-lock-rule]=*

    relevant.rule.names=\
        portal-lock-rule

    test.batch.names[relevent][portal-lock-rule]

##
## Testray
##

    testray.main.component.name=Portal Services