##
## Test Suites
##

    modified.files.includes[relevant][asset-api-rule]=**

    relevant.rule.names=\
        asset-api-rule

    test.batch.names[relevant][asset-api-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-test/**/*Test.java