##
## Test Suites
##

	test.batch.names[relevent][asset-test-rule]

	relevant.rule.names=\
		asset-test-rule

	modified.files.includes[relevant][asset-test-rule]=*
##
## Testray
##

    testray.main.component.name=Asset Framework