##
## Test Suites
##


	modified.files.includes[relevant][asset-test-rule]=**

	relevant.rule.names=\
		asset-test-rule

	test.batch.names[relevant][asset-test-rule]
##
## Testray
##

    testray.main.component.name=Asset Framework