##
## Test Suites
##

	test.batch.names[relevent][google-places-rule]

	relevant.rule.names=\
		google-places-rule

	modified.files.includes[relevant][google-places-rule]=*
##
## Testray
##

    testray.main.component.name=Forms