##
## Test Suites
##

    modified.files.includes[relevant][google-places-rule]=*

    relevant.rule.names=\
        google-places-rule

    test.batch.names[relevent][google-places-rule]

##
## Testray
##

    testray.main.component.name=Forms