##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]=\
	functional-upgrade*-tomcat*-mysql*-jdk8

relevant.rule.names=\
	knowledge-base-service-rule

modified.files.includes[relevant][knowledge-base-service-rule]=*
##
## Relevant
##

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant][knowledge-base-service-rule]=\
        (testray.component.names == "Knowledge Base") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Testray
##

    testray.main.component.name=Knowledge Base