##
## Test Suites
##

    modified.files.includes[relevant][hello-velocity-rule]=**

    relevant.rule.names=\
        hello-velocity-rule

    test.batch.names[relevant][hello-velocity-rule]

##
## Testray
##

    testray.main.component.name=Templates Engine