##
## Test Suites
##

	test.batch.names[relevent][hello-velocity-rule]

	relevant.rule.names=\
		hello-velocity-rule

	modified.files.includes[relevant][hello-velocity-rule]=*
##
## Testray
##

    testray.main.component.name=Templates Engine