##
## Test Suites
##

    modified.files.includes[relevant][gradle-plugins-app-docker-rule]=*

    relevant.rule.names=\
        gradle-plugins-app-docker-rule

    test.batch.names[relevent][gradle-plugins-app-docker-rule]

##
## Testray
##

    testray.main.component.name=Dev Tools