##
## Test Suites
##

    modified.files.includes[relevant][asset-entry-rel-test-rule]=**

    relevant.rule.names=\
        asset-entry-rel-test-rule

    test.batch.names[relevant][asset-entry-rel-test-rule]

##
## Testray
##

    testray.main.component.name=Collections