##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	asset-category-property-service-rule

modified.files.includes[relevant][asset-category-property-service-rule]=*

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-category-property-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Categories