##
## Test Suites
##


	modified.files.includes[relevant][portal-upgrade-test-rule]=*

	relevant.rule.names=\
		portal-upgrade-test-rule

	test.batch.names[relevent][portal-upgrade-test-rule]
##
## Testray
##

    testray.main.component.name=Database Upgrade Framework