##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	portal-upgrade-test-rule

modified.files.includes[relevant][portal-upgrade-test-rule]=*
##
## Testray
##

    testray.main.component.name=Database Upgrade Framework