##
## Test Suites
##


	modified.files.includes[relevant][upload-rule]=**

	relevant.rule.names=\
		upload-rule

	test.batch.names[relevant][upload-rule]
##
## Testray
##

    testray.main.component.name=Item Selector