##
## Test Suites
##
##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]=\
	functional-upgrade*-tomcat*-mysql*-jdk8

test.batch.names[relevent][testFunctional-rule]=\
	functional-upgrade*-tomcat*-mysql*-jdk8

relevant.rule.names=\
	document-library-web-rule

modified.files.includes[relevant][document-library-web-rule]=*

relevant.rule.names=\
	document-library-web-rule

modified.files.includes[relevant][document-library-web-rule]=*
##
## Relevant
##

    playwright.test.project[playwright-js-tomcat90-mysql57-jdk8][relevant][document-library-web-rule]=document-library-web

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant][document-library-web-rule]=\
        (testray.component.names == "Document Management") AND \
        (testray.main.component.name == "Upgrades Content Management")

##
## Testray
##

    testray.main.component.name=Document Management