##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	portal-url-builder-rule

modified.files.includes[relevant][portal-url-builder-rule]=*
##
## Testray
##

    testray.main.component.name=Friendly URL Service