##
## Test Suites
##


	modified.files.includes[relevant][counter-rule]=**

	relevant.rule.names=\
		counter-rule

	test.batch.names[relevant][counter-rule]
##
## Testray
##

    testray.main.component.name=Portal Services