##
## Test Suites
##

	test.batch.names[relevent][counter-rule]

	relevant.rule.names=\
		counter-rule

	modified.files.includes[relevant][counter-rule]=*
##
## Testray
##

    testray.main.component.name=Portal Services