##
## Test Suites
##


	modified.files.includes[relevant][asset-list-test-rule]=*

	relevant.rule.names=\
		asset-list-test-rule

	test.batch.names[relevent][asset-list-test-rule]
##
## Testray
##

    testray.main.component.name=Collections