##
## Test Suites
##

    modified.files.includes[relevant][petra-rule]=**

    relevant.rule.names=\
        petra-rule

    test.batch.names[relevant][petra-rule]

##
## Testray
##

    testray.main.component.name=Core Infrastructure Util