##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	petra-rule

modified.files.includes[relevant][petra-rule]=*
##
## Testray
##

    testray.main.component.name=Core Infrastructure Util