##
## Test Suites
##

    modified.files.includes[relevant][asset-vocabulary-item-selector-web-rule]=*

    relevant.rule.names=\
        asset-vocabulary-item-selector-web-rule

    test.batch.names[relevent][asset-vocabulary-item-selector-web-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Tags