##
## Test Suites
##


	modified.files.includes[relevant][json-storage-rule]=**

	relevant.rule.names=\
		json-storage-rule

	test.batch.names[relevant][json-storage-rule]
##
## Testray
##

    testray.main.component.name=Portal Services