##
## Modules
##

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-test/**/*Test.java

##
## Test Suites
##

    test.batch.names[relevent][asset-info-impl-rule]

    relevant.rule.names=\
        asset-info-impl-rule

    modified.files.includes[relevant][asset-info-impl-rule]=*