##
## Test Suites
##

    relevant.rule.names=\
        portal-model-relationship-rule

    modified.files.includes[relevant][portal-model-relationship-rule]=*

##
## Testray
##

    testray.main.component.name=Staging