##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	saved-content-rule

modified.files.includes[relevant][saved-content-rule]=*
##
## Testray
##

    testray.main.component.name=Saved Content