##
## Test Suites
##


	modified.files.includes[relevant][saved-content-rule]=**

	relevant.rule.names=\
		saved-content-rule

	test.batch.names[relevant][saved-content-rule]
##
## Testray
##

    testray.main.component.name=Saved Content