##
## Test Suites
##


	modified.files.includes[relevant][learn-rule]=**

	relevant.rule.names=\
		learn-rule

	test.batch.names[relevant][learn-rule]
##
## Testray
##

    testray.main.component.name=Setup Wizard