##
## Test Suites
##

    test.batch.names[relevent][learn-rule]

    relevant.rule.names=\
        learn-rule

    modified.files.includes[relevant][learn-rule]=*

##
## Testray
##

    testray.main.component.name=Setup Wizard