##
## Test Suites
##


	modified.files.includes[relevant][asset-entry-query-processor-custom-user-attributes-rule]=*

	relevant.rule.names=\
		asset-entry-query-processor-custom-user-attributes-rule

	test.batch.names[relevent][asset-entry-query-processor-custom-user-attributes-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-entry-rel-test/**/*Test.java