##
## Test Suites
##


	modified.files.includes[relevant][shared-dependencies-rule]=**

	relevant.rule.names=\
		shared-dependencies-rule

	test.batch.names[relevant][shared-dependencies-rule]
##
## Testray
##

    testray.main.component.name=Portal Services