##
## Test Suites
##


	modified.files.includes[relevant][connected-app-rule]=*

	relevant.rule.names=\
		connected-app-rule

	test.batch.names[relevent][connected-app-rule]
##
## Testray
##

    testray.main.component.name=Connected Apps