##
## Test Suites
##

    modified.files.includes[relevant][connected-app-rule]=**

    relevant.rule.names=\
        connected-app-rule

    test.batch.names[relevant][connected-app-rule]

##
## Testray
##

    testray.main.component.name=Connected Apps