##
## Test Suites
##


	modified.files.includes[relevant][dynamic-data-mapping-rule]=**

	relevant.rule.names=\
		dynamic-data-mapping-rule

	test.batch.names[relevant][dynamic-data-mapping-rule]=\
		functional-tomcat90-mysql157-jdk8,\
		functional-upgrade-tomcat90-mysql157-jdk8

    modules.includes.required.functional[relevant][dynamic-data-mapping-rule]=\
        apps/journal

    modules.includes.required.test.batch.class.names.includes[relevant][dynamic-data-mapping-rule]=\
        apps/document-library/document-library-test/**/*Test.java,\
        apps/journal/journal-test/**/*Test.java


    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-bundle-tomcat-mysql57-jdk8][test-portal-hotfix-release]=\
        ${test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][dynamic-data-mapping-rule]}

    #
    # Relevant
    #

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant][dynamic-data-mapping-rule]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "Forms") OR \
            (testray.component.names ~ "Site Templates") OR \
            (testray.main.component.name == "Forms")\
        )

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant][dynamic-data-mapping-rule]=\
        (data.archive.type != "data-archive-calendar") AND \
        (portal.acceptance == true) AND \
        (portal.release != "false") AND \
        (testray.main.component.name == "Upgrades Forms")

##
## Testray
##

    testray.main.component.name=Dynamic Data Lists