##
## Test Suites
##

    test.batch.names[relevent][service-component-rule]

    relevant.rule.names=\
        service-component-rule

    modified.files.includes[relevant][service-component-rule]=*

##
## Testray
##

    testray.main.component.name=Portal Services