##
## Test Suites
##


	modified.files.includes[relevant][portal-tools-bundle-support-rule]=**

	relevant.rule.names=\
		portal-tools-bundle-support-rule

	test.batch.names[relevant][portal-tools-bundle-support-rule]
##
## Testray
##

    testray.main.component.name=Dev Tools