##
## Test Suites
##

    modified.files.includes[relevant][asset-display-page-test-rule]=**

    relevant.rule.names=\
        asset-display-page-test-rule

    test.batch.names[relevant][asset-display-page-test-rule]

##
## Testray
##

    testray.main.component.name=Display Page Templates