    test.batch.names[relevent][license-manager-rule]

    relevant.rule.names=\
        license-manager-rule

    modified.files.includes[relevant][license-manager-rule]=*

##
## Testray
##

    testray.main.component.name=License