##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	license-manager-rule

modified.files.includes[relevant][license-manager-rule]=*
##
## Testray
##

    testray.main.component.name=License