##
## Test Suites
##

    modified.files.includes[relevant][license-manager-rule]=**

    relevant.rule.names=\
        license-manager-rule

    test.batch.names[relevant][license-manager-rule]

##
## Testray
##

    testray.main.component.name=License