##
## Test Suites
##


	modified.files.includes[relevant][source-formatter-rule]=*

	relevant.rule.names=\
		source-formatter-rule

	test.batch.names[relevent][source-formatter-rule]
##
## Testray
##

    testray.main.component.name=Source Formatter