##
## Test Suites
##

test.batch.names[relevent][testFunctional-rule]

relevant.rule.names=\
	source-formatter-rule

modified.files.includes[relevant][source-formatter-rule]=*
##
## Testray
##

    testray.main.component.name=Source Formatter