##
## Test Suites
##


	modified.files.includes[relevant][asset-list-api-rule]=*

	relevant.rule.names=\
		asset-list-api-rule

	test.batch.names[relevent][asset-list-api-rule]

    modules.includes.required.test.batch.class.names.includes=\
        **/asset-list-test/**/*Test.java

##
## Testray
##

    testray.main.component.name=Collections